import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>
        <li><Link href='/app' ><a>App</a></Link></li>
        <li><Link href='/devpleno' ><a>Tenant devpleno</a></Link></li>
      </ul>
    </div>
  );
};

export default Home;
